### ISSUE TITLE
NYC: PATH Routes

### ISSUE THREAD

**Issue by ezrizhu** [econaxis/time2reach#1]
The Port Authority of NY NJ operates the [Port Authority Trans Hudson](https://www.panynj.gov/path/en/index.html) train that brings people from the NWK,HOB,JC area to NYC via frequent trains. However, it is not on time2reach, and it would decrease the time to go from NYC to Hoboken from >45 min to around 10 minutes or even less.

**Comment by ezrizhu** [comment]
I did a bit of digging and found [this](https://github.com/MobilityData/mobility-database-catalogs/blob/1e96f84d52ce371ac23a6740a51a0e232e232bb3/catalogs/sources/gtfs/schedule/us-new-jersey-port-authority-trans-hudson-path-gtfs-517.json#L4), I’m not sure if it is useful or not.

**Comment by econaxis** [comment]
Thanks for this. Just added it now. You should see it live as soon as I deploy within today.

<img width="1045" alt="image" src="https://github.com/econaxis/time2reach/assets/25783926/c21cd9d2-ca94-47a3-aeb2-56e9ef3ed2a8">
