### ISSUE TITLE
Possibly leaked secrets

### ISSUE THREAD

**Issue by ddraillantclark** [econaxis/time2reach#2]
Hey,
I scanned your repo with [gitleaks](https://github.com/gitleaks/gitleaks) and it looks like you might have your GitHub PAT and an AWS access key in plain text in your code. Just wanted to give you a heads up.
Daniel

**Comment by econaxis** [comment]
Yeah I remember those haha :(. Those keys have already been rotated and no longer works. Thanks for the heads-up though!
